version: '3.9'

services:
  helloworld:
   container_name: helloworld
   build: .
   ports:
    - "8000:8000"
   environment:
    - DJANGO_SETTINGS_MODULE=helloworld.settings
   volumes:
      - .:/app
