apiVersion: v1  # Correct API version for Pod
kind: Pod
metadata:
  name: helloworld
spec:
  containers:
  - name: helloworld
    image: helloworld-helloworld:latest
    ports:
    - containerPort: 8000
